/**
 * Project Settings - General Settings (origin / development boundary months)
 *
 * Owns the canonical year-month parsing used across Project Settings, the
 * per-project General Settings cache, its `/general_settings` reads and
 * writes, and the Source Data period band editor (typing, wheel, picker commits).
 */

const MONTH_ABBR = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

const MONTH_TOKENS = {
  jan: 1, january: 1,
  feb: 2, february: 2,
  mar: 3, march: 3,
  apr: 4, april: 4,
  may: 5,
  jun: 6, june: 6,
  jul: 7, july: 7,
  aug: 8, august: 8,
  sep: 9, sept: 9, september: 9,
  oct: 10, october: 10,
  nov: 11, november: 11,
  dec: 12, december: 12,
};

export const EMPTY_GENERAL_SETTINGS = Object.freeze({
  projectName: "",
  projectFolderName: "",
  projectNameMismatch: false,
  autoGenerated: true,
  originStartDate: "",
  originEndDate: "",
  developmentEndDate: "",
});

function normalizeBoundaryIntegerText(value) {
  const raw = String(value ?? "").trim();
  if (!raw) return "";
  const compact = raw.replace(/,/g, "");
  const m = compact.match(/^(-?\d+)(?:\.0+)?$/);
  if (!m) return raw;
  const intPart = String(m[1] || "");
  const sign = intPart.startsWith("-") ? "-" : "";
  const digits = sign ? intPart.slice(1) : intPart;
  const normalizedDigits = digits.replace(/^0+(?=\d)/, "");
  return sign + normalizedDigits;
}

function normalizeYmParts(yearRaw, monthRaw) {
  const year = Number(yearRaw);
  const month = Number(monthRaw);
  if (!Number.isInteger(year) || year < 1) return "";
  if (!Number.isInteger(month) || month < 1 || month > 12) return "";
  return String(year).padStart(4, "0") + String(month).padStart(2, "0");
}

function monthTokenToNumber(token) {
  const key = String(token || "").trim().toLowerCase();
  if (!key) return null;
  return Object.prototype.hasOwnProperty.call(MONTH_TOKENS, key) ? MONTH_TOKENS[key] : null;
}

/** Parse any supported boundary spelling into canonical `YYYYMM`. */
export function normalizeBoundaryYmCanonical(value) {
  const raw = String(value ?? "").trim();
  if (!raw) return "";

  const compact = normalizeBoundaryIntegerText(raw);
  let m = compact.match(/^(\d{4})(\d{2})$/);
  if (m) return normalizeYmParts(m[1], m[2]);

  m = raw.match(/^(\d{4})\s*[-/]\s*(\d{1,2})$/);
  if (m) return normalizeYmParts(m[1], m[2]);

  m = raw.match(/^(\d{1,2})\s*[-/]\s*(\d{4})$/);
  if (m) return normalizeYmParts(m[2], m[1]);

  m = raw.match(/^([A-Za-z]{3,9})[\s,/-]+(\d{4})$/);
  if (m) {
    const month = monthTokenToNumber(m[1]);
    if (month != null) return normalizeYmParts(m[2], month);
  }

  m = raw.match(/^(\d{4})[\s,/-]+([A-Za-z]{3,9})$/);
  if (m) {
    const month = monthTokenToNumber(m[2]);
    if (month != null) return normalizeYmParts(m[1], month);
  }

  return "";
}

export function formatBoundaryYmDisplay(value) {
  const canonical = normalizeBoundaryYmCanonical(value);
  if (!canonical) return "";
  const year = canonical.slice(0, 4);
  const month = Number(canonical.slice(4, 6));
  if (!Number.isInteger(month) || month < 1 || month > 12) return "";
  return `${MONTH_ABBR[month - 1]} ${year}`;
}

export function shiftBoundaryYmCanonical(value, deltaMonths) {
  const canonical = normalizeBoundaryYmCanonical(value);
  if (!canonical) return "";
  const year = Number(canonical.slice(0, 4));
  const month = Number(canonical.slice(4, 6));
  if (!Number.isInteger(year) || !Number.isInteger(month)) return "";
  const idx = (year * 12) + (month - 1) + Number(deltaMonths || 0);
  if (!Number.isFinite(idx)) return "";
  const nextYear = Math.floor(idx / 12);
  const nextMonth = (idx % 12) + 1;
  if (nextYear < 1 || nextMonth < 1 || nextMonth > 12) return canonical;
  return normalizeYmParts(nextYear, nextMonth);
}

function normalizeGeneralSettingsBool(value, fallback = false) {
  if (typeof value === "boolean") return value;
  if (typeof value === "number") return value !== 0;
  const s = String(value ?? "").trim().toLowerCase();
  if (s === "1" || s === "true" || s === "yes" || s === "y" || s === "on") return true;
  if (s === "0" || s === "false" || s === "no" || s === "n" || s === "off") return false;
  return !!fallback;
}

/**
 * @param {object} deps
 * @param {Function} deps.setStatus
 * @param {Function} deps.normalizeProjectKey
 * @param {Function} deps.readResponseErrorDetail
 * @param {Function} deps.getSelectedProject
 * @param {Function} deps.onInputsChanged  Called after the inputs are rewritten.
 * @param {Function} deps.fetchImpl
 * @param {object} deps.controls  `{ originStartDate: {input}, ... }`
 */
export function createGeneralSettingsFeature(deps) {
  const {
    setStatus,
    normalizeProjectKey,
    readResponseErrorDetail,
    getSelectedProject,
    onInputsChanged,
    fetchImpl,
    controls,
  } = deps;

  const generalSettingsByProject = new Map();
  const controlList = Object.entries(controls || {})
    .map(([key, control]) => ({ key, ...control }))
    .filter((control) => !!control.input);

  function normalizeValues(values = {}) {
    const projectName = String(values?.projectName ?? values?.project_name ?? "").trim();
    const projectFolderName = String(values?.projectFolderName ?? values?.project_folder_name ?? "").trim();
    const inferredMismatch = (
      projectName
      && projectFolderName
      && normalizeProjectKey(projectName) !== normalizeProjectKey(projectFolderName)
    );
    return {
      projectName,
      projectFolderName,
      projectNameMismatch: normalizeGeneralSettingsBool(values?.projectNameMismatch ?? values?.project_name_mismatch, inferredMismatch),
      autoGenerated: normalizeGeneralSettingsBool(values?.autoGenerated ?? values?.auto_generated, false),
      originStartDate: normalizeBoundaryYmCanonical(values?.originStartDate ?? values?.origin_start_date ?? ""),
      originEndDate: normalizeBoundaryYmCanonical(values?.originEndDate ?? values?.origin_end_date ?? ""),
      developmentEndDate: normalizeBoundaryYmCanonical(values?.developmentEndDate ?? values?.development_end_date ?? ""),
    };
  }

  function getCache(projectName) {
    const key = normalizeProjectKey(projectName);
    if (!key) return normalizeValues(EMPTY_GENERAL_SETTINGS);
    return normalizeValues(generalSettingsByProject.get(key) || EMPTY_GENERAL_SETTINGS);
  }

  function setCache(projectName, values = {}) {
    const key = normalizeProjectKey(projectName);
    if (!key) return normalizeValues(EMPTY_GENERAL_SETTINGS);
    const normalized = normalizeValues(values);
    generalSettingsByProject.set(key, normalized);
    return normalized;
  }

  function hasValues(values = {}) {
    const v = normalizeValues(values);
    return !!(v.originStartDate || v.originEndDate || v.developmentEndDate);
  }

  function areEqual(a = {}, b = {}) {
    const left = normalizeValues(a);
    const right = normalizeValues(b);
    return (
      left.autoGenerated === right.autoGenerated
      && left.originStartDate === right.originStartDate
      && left.originEndDate === right.originEndDate
      && left.developmentEndDate === right.developmentEndDate
    );
  }

  function controlByKey(key) {
    return controlList.find((control) => control.key === key) || null;
  }

  function inputByKey(key) {
    return controlByKey(key)?.input || null;
  }

  /** Rewrite the three period inputs from canonical or free-form values. */
  function setDerivedDateInputs(values = {}) {
    const originStartInput = inputByKey("originStartDate");
    const originEndInput = inputByKey("originEndDate");
    const developmentEndInput = inputByKey("developmentEndDate");
    if (originStartInput) originStartInput.value = formatBoundaryYmDisplay(values?.originStart || "");
    if (originEndInput) originEndInput.value = formatBoundaryYmDisplay(values?.originEnd || "");
    if (developmentEndInput) developmentEndInput.value = formatBoundaryYmDisplay(values?.developmentEnd || "");
    onInputsChanged?.();
  }

  /** Apply a cached/loaded settings record to the inputs. */
  function applyValuesToInputs(values) {
    setDerivedDateInputs({
      originStart: values.originStartDate,
      originEnd: values.originEndDate,
      developmentEnd: values.developmentEndDate,
    });
  }

  function getInputValues() {
    return normalizeValues({
      originStartDate: inputByKey("originStartDate")?.value || "",
      originEndDate: inputByKey("originEndDate")?.value || "",
      developmentEndDate: inputByKey("developmentEndDate")?.value || "",
    });
  }

  function isStillSelected(name) {
    const selected = getSelectedProject();
    return !!selected && selected.name === name;
  }

  async function load(projectName, options = {}) {
    const applyToInputs = !!options?.applyToInputs;
    const name = String(projectName || "").trim();
    const empty = normalizeValues(EMPTY_GENERAL_SETTINGS);
    if (!name) return empty;

    try {
      const res = await fetchImpl(`/general_settings?project_name=${encodeURIComponent(name)}`);
      if (!res.ok) throw new Error(await readResponseErrorDetail(res));
      const out = await res.json();
      const values = setCache(name, normalizeValues(out?.data || {}));
      if (applyToInputs && isStillSelected(name)) applyValuesToInputs(values);
      return values;
    } catch (err) {
      setStatus(`Failed to load General Settings: ${err.message}`);
      const values = setCache(name, empty);
      if (applyToInputs && isStillSelected(name)) applyValuesToInputs(values);
      return values;
    }
  }

  async function ensureLoaded(projectName, options = {}) {
    const applyToInputs = !!options?.applyToInputs;
    const name = String(projectName || "").trim();
    if (!name) return normalizeValues(EMPTY_GENERAL_SETTINGS);
    const key = normalizeProjectKey(name);
    if (generalSettingsByProject.has(key)) {
      const values = getCache(name);
      if (applyToInputs && isStillSelected(name)) applyValuesToInputs(values);
      return values;
    }
    return load(name, { applyToInputs });
  }

  async function save(projectName, values = {}, options = {}) {
    const force = !!options?.force;
    const interactive = !!options?.interactive;
    const autoGenerated = normalizeGeneralSettingsBool(options?.autoGenerated, false);
    const name = String(projectName || "").trim();
    if (!name) return { ok: false, data: normalizeValues(EMPTY_GENERAL_SETTINGS) };

    const normalized = normalizeValues({ ...values, autoGenerated });
    const cached = getCache(name);
    if (!force && areEqual(cached, normalized)) {
      return { ok: true, skipped: true, data: cached };
    }

    try {
      const res = await fetchImpl("/general_settings", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          project_name: name,
          origin_start_date: normalized.originStartDate,
          origin_end_date: normalized.originEndDate,
          development_end_date: normalized.developmentEndDate,
          auto_generated: normalized.autoGenerated,
        }),
      });
      if (!res.ok) throw new Error(await readResponseErrorDetail(res));
      const out = await res.json();
      const saved = setCache(name, normalizeValues(out?.data || normalized));
      return { ok: true, data: saved };
    } catch (err) {
      setStatus(`Failed to save General Settings: ${err.message}`);
      if (interactive) {
        alert(`Failed to save General Settings: ${err.message}`);
      }
      return { ok: false, data: normalized };
    }
  }

  /** Wire typing, wheel, and picker change commits for the selected project. */
  function bindEditor(project) {
    if (controlList.length === 0 || !project?.name) return;

    let committing = false;
    let commitPending = false;
    const commitCurrentValues = async () => {
      if (committing) {
        commitPending = true;
        return;
      }
      if (!isStillSelected(project.name)) return;
      committing = true;
      try {
        const values = getInputValues();
        const cached = getCache(project.name);
        const changed = !areEqual(
          { ...cached, autoGenerated: false },
          { ...values, autoGenerated: false },
        );
        if (!changed) return;
        const out = await save(project.name, values, { autoGenerated: false });
        if (out.ok) {
          setCache(project.name, out.data || values);
        }
      } finally {
        committing = false;
        if (commitPending) {
          commitPending = false;
          commitCurrentValues();
        }
      }
    };

    const getDateInputSelectedPart = (input) => {
      const saved = String(input?.dataset?.selectedPart || "").trim().toLowerCase();
      if (saved === "month" || saved === "year") return saved;
      const start = Number(input?.selectionStart);
      if (Number.isInteger(start) && start >= 4) return "year";
      return "month";
    };

    const selectDateInputPart = (input, part) => {
      if (!input) return;
      const p = part === "year" ? "year" : "month";
      input.dataset.selectedPart = p;
      const canonical = normalizeBoundaryYmCanonical(input.value);
      if (!canonical) return;
      const start = p === "year" ? 4 : 0;
      const end = p === "year" ? 8 : 3;
      try {
        input.setSelectionRange(start, end);
      } catch {
        // ignore selection failures in non-focus state
      }
    };

    const adjustDateInputBySelectedPart = (input, fallbackCanonical, delta) => {
      const base = normalizeBoundaryYmCanonical(input.value) || normalizeBoundaryYmCanonical(fallbackCanonical);
      if (!base) return "";
      const part = getDateInputSelectedPart(input);
      const monthDelta = part === "year" ? (Number(delta || 0) * 12) : Number(delta || 0);
      const shifted = shiftBoundaryYmCanonical(base, monthDelta);
      if (!shifted) return "";
      input.value = formatBoundaryYmDisplay(shifted);
      selectDateInputPart(input, part);
      return shifted;
    };

    for (const control of controlList) {
      const input = control.input;
      const getFallbackCanonical = () => {
        const cached = getCache(project.name);
        return normalizeBoundaryYmCanonical(cached?.[control.key] || "");
      };

      const normalizeInputDisplay = () => {
        const canonical = normalizeBoundaryYmCanonical(input.value) || getFallbackCanonical();
        const part = getDateInputSelectedPart(input);
        input.value = formatBoundaryYmDisplay(canonical);
        if (canonical) selectDateInputPart(input, part);
        return canonical;
      };

      input.disabled = false;
      input.onfocus = () => {
        if (!input.value) return;
        selectDateInputPart(input, getDateInputSelectedPart(input));
      };
      input.onclick = () => {
        setTimeout(() => {
          const caret = Number(input.selectionStart);
          const part = Number.isInteger(caret) && caret >= 4 ? "year" : "month";
          selectDateInputPart(input, part);
        }, 0);
      };
      input.onkeydown = (e) => {
        if (e.key === "Enter") {
          e.preventDefault();
          input.blur();
        }
      };
      input.onwheel = (e) => {
        if (!isStillSelected(project.name)) return;
        const delta = e.deltaY < 0 ? 1 : -1;
        const changed = adjustDateInputBySelectedPart(input, getFallbackCanonical(), delta);
        if (!changed) return;
        e.preventDefault();
        commitCurrentValues();
      };
      input.onblur = () => {
        normalizeInputDisplay();
        commitCurrentValues();
      };
      input.onchange = () => {
        normalizeInputDisplay();
        commitCurrentValues();
      };
    }
  }

  /** Drop every cached record, e.g. when the project map is reloaded. */
  function clearCache() {
    generalSettingsByProject.clear();
  }

  return {
    bindEditor,
    clearCache,
    ensureLoaded,
    getCache,
    hasValues,
    save,
    setDerivedDateInputs,
  };
}
