const qs = new URLSearchParams(window.location.search);

export const DATASET_TABLE_COLUMNS = Object.freeze([
  { key: "name", label: "Name", minWidth: 150 },
  { key: "status", label: "Status", minWidth: 52 },
  { key: "datasetTypeName", label: "Dataset Type Name", minWidth: 150 },
  { key: "dataFormat", label: "Data Format", minWidth: 120 },
  { key: "formula", label: "Formula", minWidth: 160 },
  { key: "category", label: "Category", minWidth: 120 },
  { key: "methodType", label: "Method Type", minWidth: 110 },
  { key: "lastModified", label: "Last Modified", minWidth: 130 },
  { key: "created", label: "Created", minWidth: 110 },
  { key: "user", label: "User", minWidth: 110 },
]);

export const DATASET_TABLE_DEFAULT_WIDTHS = Object.freeze({
  name: 342,
  status: 69,
  datasetTypeName: 301,
  dataFormat: 142,
  formula: 330,
  category: 133,
  methodType: 137,
  lastModified: 151,
  created: 142,
  user: 129,
});

export const DATASET_TABLE_DEFAULT_COLUMN_ORDER = Object.freeze([
  "status",
  "name",
  "dataFormat",
  "category",
  "methodType",
  "user",
  "lastModified",
  "created",
  "datasetTypeName",
  "formula",
]);

export const DATASET_TABLE_DEFAULT_GROUP_BY = Object.freeze([
  "dataFormat",
  "category",
]);

export function createProjectInstanceContext(deps = {}) {
  const projectName = String(qs.get("project") || "").trim();
  const els = {
    root: document.getElementById("projectInstanceRoot"),
    toolbar: document.querySelector(".pi-toolbar"),
    layout: document.querySelector(".pi-layout"),
    leftPanel: document.querySelector(".pi-left"),
    rightPanel: document.querySelector(".pi-right"),
    leftPanelResizer: document.getElementById("leftPanelResizer"),
    pathTree: document.getElementById("pathTree"),
    selectedPathText: document.getElementById("selectedPathText"),
    pathContextMenu: document.getElementById("pathContextMenu"),
    hiddenTabsWrap: document.getElementById("hiddenTabsWrap"),
    hiddenTabsList: document.getElementById("hiddenTabsList"),
    hiddenTabsButton: document.getElementById("hiddenTabsButton"),
    hiddenTabsLabel: document.getElementById("hiddenTabsLabel"),
    hiddenTabsMenu: document.getElementById("hiddenTabsMenu"),
    datasetRefreshBtn: document.getElementById("datasetRefreshBtn"),
    datasetNumberFormatsBtn: document.getElementById("datasetNumberFormatsBtn"),
    datasetNumberFormatsOverlay: document.getElementById("datasetNumberFormatsOverlay"),
    datasetNumberFormatsWindow: document.getElementById("datasetNumberFormatsWindow"),
    datasetNumberFormatsHeader: document.getElementById("datasetNumberFormatsHeader"),
    datasetNumberFormatsClose: document.getElementById("datasetNumberFormatsClose"),
    datasetNumberFormatsPath: document.getElementById("datasetNumberFormatsPath"),
    datasetNumberFormatsDefault: document.getElementById("datasetNumberFormatsDefault"),
    datasetNumberFormatsFilter: document.getElementById("datasetNumberFormatsFilter"),
    datasetNumberFormatsAdd: document.getElementById("datasetNumberFormatsAdd"),
    datasetNumberFormatsBody: document.getElementById("datasetNumberFormatsBody"),
    datasetNumberFormatsEmpty: document.getElementById("datasetNumberFormatsEmpty"),
    datasetNumberFormatsStatus: document.getElementById("datasetNumberFormatsStatus"),
    datasetNumberFormatsCancel: document.getElementById("datasetNumberFormatsCancel"),
    datasetNumberFormatsSave: document.getElementById("datasetNumberFormatsSave"),
    datasetTempViewBtn: document.getElementById("datasetTempViewBtn"),
    datasetTempViewTooltipTitle: document.getElementById("datasetTempViewTooltipTitle"),
    datasetTempViewTooltipDescription: document.getElementById("datasetTempViewTooltipDescription"),
    datasetIndexUpdateBtn: document.getElementById("datasetIndexUpdateBtn"),
    datasetGroupByStatus: document.getElementById("datasetGroupByStatus"),
    datasetActiveFilters: document.getElementById("datasetActiveFilters"),
    cachedDatasetStatus: document.getElementById("cachedDatasetStatus"),
    pageLoadingOverlay: document.getElementById("pageLoadingOverlay"),
    pageLoadingTitle: document.getElementById("pageLoadingTitle"),
    pageLoadingMessage: document.getElementById("pageLoadingMessage"),
    pageLoadingElapsed: document.getElementById("pageLoadingElapsed"),
    datasetTableWrap: document.getElementById("datasetTableWrap"),
    datasetTableSurface: document.getElementById("datasetTableSurface"),
    datasetTableContextMenu: document.getElementById("datasetTableContextMenu"),
    datasetGroupContextMenu: document.getElementById("datasetGroupContextMenu"),
    datasetRowContextMenu: document.getElementById("datasetRowContextMenu"),
    datasetAddPickerOverlay: document.getElementById("datasetAddPickerOverlay"),
    datasetAddPickerBox: document.getElementById("datasetAddPickerBox"),
    datasetAddPickerClose: document.getElementById("datasetAddPickerClose"),
    datasetAddPickerNameSearch: document.getElementById("datasetAddPickerNameSearch"),
    datasetAddPickerStatus: document.getElementById("datasetAddPickerStatus"),
    datasetAddPickerTableWrap: document.getElementById("datasetAddPickerTableWrap"),
    datasetAddPickerTable: document.getElementById("datasetAddPickerTable"),
    datasetAddPickerEmpty: document.getElementById("datasetAddPickerEmpty"),
    datasetAddPickerFilterPopover: document.getElementById("datasetAddPickerFilterPopover"),
    datasetTableFilterPopover: document.getElementById("datasetTableFilterPopover"),
    datasetDeleteConfirmOverlay: document.getElementById("datasetDeleteConfirmOverlay"),
    datasetDeleteConfirmBox: document.getElementById("datasetDeleteConfirmBox"),
    datasetDeleteConfirmMessage: document.getElementById("datasetDeleteConfirmMessage"),
    datasetDeleteConfirmList: document.getElementById("datasetDeleteConfirmList"),
    datasetDeleteConfirmDelete: document.getElementById("datasetDeleteConfirmDelete"),
    datasetDeleteConfirmCancel: document.getElementById("datasetDeleteConfirmCancel"),
    datasetDeleteConfirmClose: document.getElementById("datasetDeleteConfirmClose"),
    datasetAddMessageOverlay: document.getElementById("datasetAddMessageOverlay"),
    datasetAddMessageBox: document.getElementById("datasetAddMessageBox"),
    datasetAddMessageTitle: document.getElementById("datasetAddMessageTitle"),
    datasetAddMessageText: document.getElementById("datasetAddMessageText"),
    datasetAddMessageOk: document.getElementById("datasetAddMessageOk"),
    datasetAddMessageClose: document.getElementById("datasetAddMessageClose"),
    windowLayer: document.getElementById("datasetWindowLayer"),
  };
  const constants = {
    DATASET_TABLE_COLUMNS,
    DATASET_COLUMNS: DATASET_TABLE_COLUMNS.length,
    DATASET_TABLE_DEFAULT_WIDTHS,
    DATASET_TABLE_AUTOFIT_MAX_WIDTH: 460,
    DATASET_TABLE_AUTOFIT_CELL_EXTRA_WIDTH: 38,
    DATASET_TABLE_AUTOFIT_HEADER_EXTRA_WIDTH: 76,
    DATASET_TABLE_BLANK_LABEL: "(Blank)",
    LEFT_PANEL_DEFAULT_WIDTH: 400,
    LEFT_PANEL_MIN_WIDTH: 200,
    LEFT_PANEL_MAX_WIDTH: 600,
    LEFT_PANEL_COLLAPSE_THRESHOLD: 200,
    LEFT_PANEL_RIGHT_MIN_WIDTH: 420,
    LEFT_PANEL_KEYBOARD_STEP: 24,
    DATASET_WINDOW_MIN_WIDTH: 420,
    DATASET_WINDOW_MIN_HEIGHT: 280,
    DATASET_WINDOW_DEFAULT_WIDTH_RATIO: 0.8,
    DATASET_WINDOW_DEFAULT_HEIGHT_RATIO: 0.8,
    DATASET_WINDOW_DOCK_ANIMATION_MS: 520,
    DATASET_WINDOW_RESTORE_ANIMATION_MS: 280,
    DATASET_WINDOW_EDGE_VISIBLE_WIDTH: 80,
    DATASET_WINDOW_TITLEBAR_HEIGHT: 30,
    HIDDEN_TABS_HOVER_CLOSE_MS: 1000,
  };
  const state = {
    selectedPath: "",
    pathPickerController: null,
    pathPickerModel: null,
    datasetRows: [],
    nextWindowZ: 1,
    windowSeq: 1,
    lastExpandedLeftWidth: constants.LEFT_PANEL_DEFAULT_WIDTH,
    lastDatasetWindowSize: null,
    activeDatasetWindow: null,
    projectInstancePageFocused: false,
    lastDatasetWindowShortcutCloseAt: 0,
    hiddenWindows: new Map(),
    datasetWindows: new Map(),
    lastZoomDetail: null,
    pageLoadingTasks: new Set(),
    hiddenTabsHoverCloseTimer: 0,
    hiddenTabsMenuPinned: false,
    minimizedTabTooltip: null,
    pageLoadingFrameTimer: 0,
    pageLoadingStartedAt: 0,
    pendingProjectInstanceRestoreState: null,
    projectInstanceBootComplete: false,
    datasetTablePreferencesLoaded: false,
    datasetTablePreferenceWidthKeys: new Set(),
    datasetTableView: {
      groupBy: [...DATASET_TABLE_DEFAULT_GROUP_BY],
      columns: [...DATASET_TABLE_DEFAULT_COLUMN_ORDER],
      widths: { ...DATASET_TABLE_DEFAULT_WIDTHS },
      filters: new Map(),
      collapsedGroups: new Set(),
      sort: { key: "", dir: "asc" },
    },
    datasetViewMode: "normal",
    temporaryDatasetSessionId: "",
    cachedDatasetFilter: {
      loading: false,
      loadedPath: "",
      names: new Set(),
      instanceRows: [],
      metadataByName: new Map(),
      methodTypesByName: new Map(),
      visibleCount: 0,
      error: "",
      warning: "",
      requestSeq: 0,
    },
    cachedDatasetSnapshotRequests: new Map(),
    datasetIndexWatch: {
      watchId: "",
      path: "",
      selectedPath: "",
      pending: false,
      error: "",
      suppressUntil: 0,
      unsubscribe: null,
    },
    datasetTableFilterColumn: "",
    datasetTableFilterSearchText: "",
    datasetTableFilterAnchor: null,
    datasetTableFilterOpenMode: "",
    datasetTableFilterHoverCloseTimer: 0,
    datasetTableFilterHoveringTrigger: false,
    datasetTableFilterHoveringPopover: false,
    datasetTableExplicitAllFilterKeys: new Set(),
    datasetTableFilterDragSourceKey: "",
    datasetTableColumnDragStarted: false,
    datasetGroupContextId: "",
    datasetRowContextKey: "",
    datasetAddPickerResolve: null,
    datasetAddPickerView: {
      search: "",
      filters: new Map(),
      sort: { key: "datasetTypeName", dir: "asc" },
      filterColumn: "",
      filterAnchor: null,
    },
    datasetTableVisibleRecords: [],
    datasetTableSelection: { selectedKeys: new Set(), anchorKey: "" },
    temporaryDatasetTableFilterState: null,
    datasetDeleteConfirmResolve: null,
    lastDatasetSelectionStatusCount: 0,
    datasetTableMeasureCanvas: null,
  };

  return {
    ...deps,
    projectName,
    els,
    constants,
    state,
    api: {},
  };
}
