from __future__ import annotations

import re

from .core import _normalize_import_name


DEFAULT_NUMBER_FORMAT = "0,000"
DEFAULT_DECIMAL_PLACES = 0

COL_RESERVING_CLASS_PATH = r"PRNJ - PA\PA\All States\Direct Group\COL"

# Manual per-instance overrides for sidecars generated by the ResQ migration.
# Edit values here when a dataset instance needs a display format other than the
# migration default.
DATASET_INSTANCE_NUMBER_FORMATS_BY_RC: dict[str, dict[str, str]] = {
    COL_RESERVING_CLASS_PATH: {
        "ALAE--as % of Gross Paid Loss": "0.0%",
        "ALAE--as % of Net Paid Loss": "0.0%",
        "ALAE--Paid": "0,000",
        "C 12 - CWP DFM w/ Selected LDFs": "0,000",
        "C 22 - CWOP DFM w/ Selected LDFs": "0,000",
        "C 32 - Reported DFM w/ Selected LDFs": "0,000",
        "C 41 - BF Reported ex CWOP": "0,000",
        "C 42 - Reported ex CWOP DFM w/ Selected LDFs": "0,000",
        "C 42a - Prior for BF Reported ex CWOP": "0,000",
        "C 43 - DFM for BF Reported ex CWOP": "0,000",
        "C 52 - CWOP/Reported DFM w/ Selected LDFs": "0,000",
        "C 61 Reported - CWOP": "0,000",
        "C 62 Reported *(CWOP/Reported) CDF": "0,000",
        "C 81 - Prior Qtr Indicated": "0,000",
        "C 82 - Prior Qtr Selected": "0,000",
        "C 91 - Current Qtr Indicated": "0,000",
        "C 92 - Current Qtr Selected": "0,000",
        "Claim Counts--Closed as % of Reported": "0.0%",
        "Claim Counts--CWOP": "0,000",
        "Claim Counts--CWP": "0,000",
        "Claim Counts--CWP as % of Reported": "0.0%",
        "Claim Counts--CWP as % of Reported ex CWOP": "0.0%",
        "Claim Counts--CWP Excess of 100K": "0,000",
        "Claim Counts--CWP Excess of 1M": "0,000",
        "Claim Counts--CWP Excess of 50K": "0,000",
        "Claim Counts--Pending": "0,000",
        "Claim Counts--Pending as % of Reported": "0.0%",
        "Claim Counts--Pending as % of Reported x CWOP": "0.0%",
        "Claim Counts--Reported": "0,000",
        "Claim Counts--Reported ex CWOP": "0,000",
        "Claim Counts--Reported Excess of 100K": "0,000",
        "Claim Counts--Reported Excess of 1M": "0,000",
        "Claim Counts--Reported Excess of 50K": "0,000",
        "Claim Counts--Total Closed": "0,000",
        "CWOP as % of Reported Claims": "0.0%",
        "D 13 - Paid DFM w/ Selected LDFs": "0,000",
        "D 18 - BS Paid DFM": "0,000",
        "D 23 - Incurred DFM w/ Selected LDFs": "0,000",
        "D 41 - BF Incurred": "0,000",
        "D 42 - Prior for BF Incurred": "0,000",
        "D 53 - Cape Cod Gross Loss Incurred": "0,000",
        "D 81 - Prior Qtr Indicated": "0,000",
        "D 82 - Prior Qtr Selected": "0,000",
        "D 91 - Current Qtr Indicated": "0,000",
        "D 92 - Current Qtr Selected": "0,000",
        "E1 12 - Salv DFM w/ Selected LDFs": "0,000",
        "E1 22 - Salv/Paid Loss DFM w/ Selected LDFs": "0,000",
        "E1 41 - BF Paid": "0,000",
        "E1 42 - Prior for BF Paid": "0,000",
        "E1 81 - Prior Qtr Indicated": "0,000",
        "E1 82 - Prior Qtr Selected": "0,000",
        "E1 91 - Current Qtr Indicated": "0,000",
        "E1 92 - Current Qtr Selected": "0,000",
        "E2 12 - Subr DFM w/ Selected LDFs": "0,000",
        "E2 22 - Subr/Paid Loss DFM w/ Selected LDFs": "0,000",
        "E2 41 - BF Paid": "0,000",
        "E2 42 - Prior for BF Paid": "0,000",
        "E2 81 - Prior Qtr Indicated": "0,000",
        "E2 82 - Prior Qtr Selected": "0,000",
        "E2 91 - Current Qtr Indicated": "0,000",
        "E2 92 - Current Qtr Selected": "0,000",
        "Earned Exposure": "0,000",
        "Earned Premium": "0,000",
        "F 25 - Incurred DFM Bootstrap": "0,000",
        "F 72 A - Bootstrap Net incurred with PV": "0,000",
        "F 72B - Bootstrap Net Incurred no PV": "0,000",
        "F 92 - Current Qtr Selected": "0,000",
        "Frequency--CWP Claim per Earned Exposure": "0.000",
        "Frequency--Reported Claim per Earned Exposure": "0.000",
        "Frequency--Reported ex CWOP per Earned Exposure": "0.000",
        "G 12 - ALAE--Paid DFM w/ Selected LDFs": "0,000",
        "G 22 A - ALAE/Gross Paid Loss DFM w/ Selected LDFs": "0,000",
        "G 81 - Prior Qtr Indicated": "0,000",
        "G 82 - Prior Qtr Selected": "0,000",
        "G 91 - Current Qtr Indicated": "0,000",
        "G 92 - Current Qtr Selected": "0,000",
        "Gross Loss--Incurred": "0,000",
        "Gross Loss--OS": "0,000",
        "Gross Loss--Paid": "0,000",
        "Gross Loss--Paid - B&S Settlement Rate Adjustment": "0,000",
        "H 01 - Gross Incurred per Reported ex CWOP DFM w/ Selected LDFs": "0,000",
        "Losses--Gross Paid as % of Gross Incurred": "0.0%",
        "Losses--Net Paid as % of Net Incurred": "0.0%",
        "Net Loss--Incurred": "0,000",
        "Net Loss--Incurred Capped at 100K": "0,000",
        "Net Loss--Incurred Capped at 1M": "0,000",
        "Net Loss--Incurred Capped at 50K": "0,000",
        "Net Loss--OS": "0,000",
        "Net Loss--Paid": "0,000",
        "Net Loss--Paid Capped at 100K": "0,000",
        "Net Loss--Paid Capped at 1M": "0,000",
        "Net Loss--Paid Capped at 50K": "0,000",
        "P 02 Salvage--Expected % of Ultimate Gross Loss - Indicated": "0.0%",
        "P 03 Subro--Expected % of Ultimate Gross Loss - Indicated": "0.0%",
        "P 04 A-ALAE--Expected % of Ultimate Gross Loss - Indicated": "0.0%",
        "Pure Premium--Gross Incurred per Earned Exposure": "0,000",
        "Pure Premium--Gross Paid per Earned Exposure": "0,000",
        "Pure Premium--Net Incurred per Earned Exposure": "0,000",
        "Pure Premium--Net Paid per Earned Exposure": "0,000",
        "Recoveries/as % of Gross Paid Loss": "0.0%",
        "Recoveries--Received": "0,000",
        "Remaining Budget Exposure": "0,000",
        "Remaining Budget Premium": "0,000",
        "Salvage--as % of Gross Paid Loss": "0.0%",
        "Salvage--Received": "0,000",
        "Severity--Case Reserve per Pending Claim": "0,000",
        "Severity--Gross Incurred per Reported": "0,000",
        "Severity--Gross Incurred per Reported ex CWOP": "0,000",
        "Severity--Gross Paid per CWP": "0,000",
        "Severity--Net Incurred per Reported": "0,000",
        "Severity--Net Incurred per Reported ex CWOP": "0,000",
        "Severity--Net Paid per CWP": "0,000",
        "Subro--as % of Gross Paid Loss": "0.0%",
        "Subro--Received": "0,000",
        "Total Earned Exposure": "0,000",
        "Total Earned Premium": "0,000",
    },
}


def dataset_instance_number_format(rc_path: object, dataset_name: object) -> str:
    rc_key = _normalize_import_name(rc_path).casefold()
    dataset_key = _normalize_import_name(dataset_name).casefold()
    for configured_rc, formats in DATASET_INSTANCE_NUMBER_FORMATS_BY_RC.items():
        if _normalize_import_name(configured_rc).casefold() != rc_key:
            continue
        for configured_name, number_format in formats.items():
            if _normalize_import_name(configured_name).casefold() == dataset_key:
                return _normalize_number_format(number_format)
    return DEFAULT_NUMBER_FORMAT


def dataset_instance_decimal_places(rc_path: object, dataset_name: object) -> int:
    return number_format_decimal_places(dataset_instance_number_format(rc_path, dataset_name))


def number_format_decimal_places(value: object) -> int:
    text = _normalize_number_format(value)
    numeric = _numeric_pattern(text)
    dot_index = numeric.find(".")
    if dot_index < 0:
        return DEFAULT_DECIMAL_PLACES
    return max(0, min(6, len(numeric[dot_index + 1:])))


def _normalize_number_format(value: object) -> str:
    text = str(value or "").replace("\r", " ").replace("\n", " ").replace("\t", " ").strip()
    return (text or DEFAULT_NUMBER_FORMAT)[:64]


def _numeric_pattern(value: str) -> str:
    match = re.search(r"[0#,]+(?:\.[0#]+)?", value)
    return match.group(0) if match else DEFAULT_NUMBER_FORMAT
